import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Toaster } from "sonner";

import { AuthProvider } from "@/lib/providers/auth-provider";
import ReactQueryProvider from "@/lib/providers/react-query-provider";
import { ThemeProvider } from "@/lib/providers/theme-provider";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Livestream App",
    description: "Generated by team TLCN",
};

function PreconnectLinks() {
    return (
        <>
            {/* Stream.io APIs */}
            <link
                rel="preconnect"
                href="https://faye-us-east.stream-io-api.com"
                crossOrigin=""
            />

            {/* CDN Resources */}
            <link
                rel="preconnect"
                href="https://lh3.googleusercontent.com"
                crossOrigin=""
            />
            <link
                rel="preconnect"
                href="https://pub-6150734308204bf898283cd938e34668.r2.dev"
                crossOrigin=""
            />

            {/* Google services */}
            <link
                rel="preconnect"
                href="https://fonts.googleapis.com"
                crossOrigin=""
            />
            <link
                rel="preconnect"
                href="https://fonts.gstatic.com"
                crossOrigin=""
            />
        </>
    );
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <PreconnectLinks />
            </head>
            <body className={inter.className}>
                <ReactQueryProvider>
                    <AuthProvider>
                        <ThemeProvider
                            attribute="class"
                            defaultTheme="dark"
                            enableSystem
                        >
                            <NuqsAdapter>
                                <Toaster theme="light" />
                                {children}
                            </NuqsAdapter>
                        </ThemeProvider>
                    </AuthProvider>
                </ReactQueryProvider>
            </body>
        </html>
    );
}
